### ISSUE TITLE
How it can be implemented by liveserver?

### ISSUE THREAD

**Issue by johndavemanuel** [7img/simple-grunt-starter#2]
I came from gulp.js, and wondering how can I put a live server, like localhost:8080 to server the "dist" folder, and auto reload when src is change

**Comment by 7img** [comment]
You would need something like: https://github.com/tapio/live-server and point it to the `dist` folder. With the live reload option it should reload on every change.

**Comment by johndavemanuel** [comment]
Do you mind how it can be integrated with grunt? 
https://github.com/gruntjs/grunt-contrib-connect#keepalive

I use this, it servers the dist folder but it does not live reload

**Comment by 7img** [comment]
Have you connected the correct port with these packages?
https://github.com/gruntjs/grunt-contrib-connect#livereload
https://github.com/gruntjs/grunt-contrib-watch#optionslivereload

**Comment by johndavemanuel** [comment]
I already made it working,  the host is wrong.
